# Generated by Django 3.2.7 on 2021-09-28 13:16

import digiloc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiloc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='file',
            field=models.FileField(upload_to='', validators=[digiloc.validators.validate_file_extension]),
        ),
    ]
