# Generated by Django 3.2.7 on 2021-09-29 05:27

import digiloc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiloc', '0002_alter_metadata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='file',
            field=models.FileField(upload_to='files/', validators=[digiloc.validators.validate_file_extension]),
        ),
    ]
